.\" Process this file with
.\" groff -man -Tascii tsh.1
.\"
.TH TSH 2 "OCTOBER 2011" "NU EECS 343" "NU EECS 343 - Operating Systems - Fall 2011"
.SH NAME
tsh \- A tiny shell
.SH SYNOPSIS
.B tsh is a tiny implementation of a shell. 
.SH DESCRIPTION
.B
The shell implements most of the Porject 2 spec, but does not implement IO
redirection, or the extra credit
.SH BUILT-IN COMMANDS
.IP exit,
cd,
bg,
fg,
jobs
.SH DESIGN APPROACH
We chose to keep as much as the provided framework as possible. We also tried
to abstract functions that would be used multiple times, while sacrificing some
efficiency to promote readability. We ran into issues in a number of areas,
mainly concerning memory management and passing pointers.
.SH AUTHOR
Aaron Steinfeld and Michael Nussbaum
ams303 and min501
asteinfeld@u.northwestern.edu and michaelnussbaum08@gmail.com
